### ISSUE TITLE
Wallet Connect doesn't work testing on live.sovryn.app

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#520]
RWallet 1.3.1 on Android

How to reproduce: Go to https://live.sovryn.app/ click on Connect Wallet, choose mobile and scan the qrcode with RWallet.

What happens: Show an option to connect to Sovryn, I accept, the app is connected but the Qrcode do not disappear.

Expected result: Sovryn be really connected with Rwallet.

**Comment by chrisli30** [comment]
This is related to PR #506 

Sovryn is on Testnet right now. I've talked to them. The best solution is that RWallet enable both Testnet in addition to Mainnet, so the app can work with Sovryn.

**Comment by bitcoinuser** [comment]
> Sovryn is on Testnet right now

I'm testing Sovryn on mainnet using https://live.sovryn.app/ and Wallet Connect on RWallet do not work. So it's not testnet.

**Comment by chrisli30** [comment]
@bitcoinuser  We have found the same issue with rskswap. The rskswap/sovryn app can respond to QR code scan in rwallet development mode, but not with the build APK. When we scan the QR code with an APK the Dapp doesn't receive a connection message from the wallet connect server.

Root cause is not identified yet. We are working on it.
