### ISSUE TITLE
Proposal: alert user about Ethereum checksum, no checksum, and empty record before sending funds 

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#522]
## Problem
When user copy paste an address with invalid checksum, they are rejected to send because the recipient address is not a valid RSK address. The app should be more user friendly and help normal user understand the problem and solve it.

## Solution
For user input with no checksum at all, we first prompt a modal to notify them that the recipient address is in invalid format and will be converted in to RSK address format(at this point the user has already chosen to use Mainnet or Testnet tokens). 

Then we will check if the recipient has records in explorer. If not we will prompt another modal to warn the sender.

The "Why are you seeing this" links to RSK developers page https://developers.rsk.co/rsk/architecture/account-based/

![image](https://user-images.githubusercontent.com/2616844/95370016-0c050a80-088d-11eb-92f6-3bcd2c5ac6c0.png)

If the address is copied from wallets such as Metamask, we alert user with a slightly different message notifying them that the Ethereum address format needs to be corrected.

![image](https://user-images.githubusercontent.com/2616844/95370132-2f2fba00-088d-11eb-8a3b-c70b56c32547.png)

**Comment by bguiz** [comment]
(1) 

This has designs for the following scenarios:

- all lower case address
- address with mixed uppercase and lowercase --> validates as an Ethereum checksum

However, there isn't any flow defined for these scenarios:

- address with mixed uppercase and lowercase --> validates as neither an Ethereum checksum nor an RSK checksum
  - in this case we should just totally reject the input and ask the user to get a correct address, and disable the confirm/ send buttons
- address with mixed uppercase and lowercase --> validates as an RSK checksum
  - in this case there is no problem, and we do not display any errors and allow the user to proceed without any warnings

(2)

If the checksum was wrong, and needed to be converted, and then subsequently, it detects that this account has no transaction history, I think the warning **needs to be more difficult** for the user.

I would suggest, for example, make the user tap a checkbox that says "I understand that may result in a loss of funds, and that there is no way to recover them". Only after that box is checked, enable the confirm button.

This is important because this flow is the one where users are the most likely to lose their funds through an "accidental burn" by transferring to an address that they are not able to sign transactions on. The worst UX for a wallet is losing funds, so I think making this particular flow more difficult for the users is more than justified.

(3)

When a user clicks on "why are you seeing this message", what happens?
Note that there are two different scenarios in which they see this.
Let's define what happens in each case.

(4)

In the first flow, where the input is all lower case, we should not say "is an invalid RSK address" as this is a technically incorrect claim. Wallets simply treat the all lowercase scenario as a "legacy address", which is turn is treated as a "skip the checksum validation" flag. As such, the message should be modified to state that we're converting it to add a checksum as there is none present, or something to that effect.

This [coinbase FAQ page](https://help.coinbase.com/en/custody/storing-on-custody/asset-transfers/address-formatting-standards#what-is-eip-55) has some helpful text which I think we can adopt.

(4)

Proof reading: "uppser-case" --> "upper-case"

**Comment by bgorlick** [comment]
ACK to @bguiz comments.

Coinbase adopted the EIP-55 standard for addresses because it puts a combination of upper-case and lower-case letters into the address to reduce risk of loss of funds, when users would sometimes send funds to an address in all upper-case when it should have been all lower-case, etc.

Regarding number (4), we should specify that all lowercase addresses are considered legacy addresses. 

@bguiz How about the following message below:
**The address you're attempting to use is in all lowercase which is a legacy address format. We are converting the address to add a checksum as there is none present to help protect users from loss of funds.**

**Comment by bguiz** [comment]
> Regarding number (4), we should specify that all lowercase addresses are considered legacy addresses.
> 
> @bguiz How about the following message below:
> **The address you're attempting to use is in all lowercase which is a legacy address format. We are converting the address to add a checksum as there is none present to help protect users from loss of funds.**

@bgorlick yes, that works for me!

**Comment by chrisli30** [comment]
I think we can put that message in the "Why are you seeing this" tooltips. The message is better than the description on developer.rsk.co webpage. 

## Proposal version 2, 4 scenarios

### Send to all lower case address
![image](https://user-images.githubusercontent.com/2616844/96035133-754dc600-0e17-11eb-8824-f1f0a444f9ef.png)

### Send to Ethereum address
![image](https://user-images.githubusercontent.com/2616844/96035166-7d0d6a80-0e17-11eb-9ab4-508e08dda13e.png)

### Send to empty record Mainnet address
![image](https://user-images.githubusercontent.com/2616844/96035182-84cd0f00-0e17-11eb-95ea-dd44a2c0db06.png)

### Send to empty record Testnet address
![image](https://user-images.githubusercontent.com/2616844/96035209-8eef0d80-0e17-11eb-974e-74477b1a8a31.png)

**Comment by bgorlick** [comment]
@chrisli30 I think we should consider reversing the order of the buttons here so that:

"Go back and re-enter" is the first option
"Send anyway" is the second option

Also, should we change "Okay, send anyway" to say "I understand the risks. Send anyway."

**Comment by bguiz** [comment]
Still reckon it'd be best if we disable all of the "send anyway" buttons until the user checks a checkbox saying "I understand the risks" or similar.

Also:
"This is a known bug for copied value from MetaMask" --> "This is a known issue when copying addresses from MetaMask"

**Comment by chrisli30** [comment]
> @chrisli30 I think we should consider reversing the order of the buttons here so that:
> 
> "Go back and re-enter" is the first option
> "Send anyway" is the second option
> 
> Also, should we change "Okay, send anyway" to say "I understand the risks. Send anyway."

The "Go back and re-enter" is the first option, which should be at the bottom because that's the easiest to click on.

**Comment by chrisli30** [comment]
> Still reckon it'd be best if we disable all of the "send anyway" buttons until the user checks a checkbox saying "I understand the risks" or similar.
> 
> Also:
> "This is a known bug for copied value from MetaMask" --> "This is a known issue when copying addresses from MetaMask"

The check box is a good suggestion. We are taking that.

**Comment by imstar15** [comment]
PR #549
